
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/web_developers_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    openInView: false
    show_sql: true
    generate-ddl: true
  data:
    jpa:
      repositories.enabled: true